version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: curl -Lo kind-linux-amd64 https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
     - run: chmod +x kind-linux-amd64
     - run: ./kind-linux-amd64 create cluster
     - run: KUBECONFIG="$(kind get kubeconfig-path --name="kind")" kubectl cluster-info
